In [37]:
import os
import deeptile
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from deeptile.extensions import segmentation
from deeptile.extensions import stitch
matplotlib.rcParams['figure.dpi'] = 300
from tifffile import TiffFile
import tifffile
import dask.array as da

In [143]:
root = "/Users/hannahbolen/Desktop/image_analysis/"
# img_name = 'o8p_day18_s22.tif'
# img_name = 'o8p_day18.vsi'
img_name = "o8p_day24_s12.ome.tif"
img_path = os.path.join(root, img_name)
img = da.from_array(tifffile.imread(img_path))
dt = deeptile.load(img)

In [ ]:
# # read in image
# root = "/Users/hannahbolen/Desktop/image_analysis/"
# img_name = "o8p_day24_s12.ome.tif"
# img_path = os.path.join(root, img_name)
# img = da.from_zarr(tifffile.imread(img_path, aszarr=True))

with TiffFile(img_path) as tif:
    # volume = tif.asarray()
    # imagej_metadata = tif.imagej_metadata
    for i, page in enumerate(tif.pages):
        print("\nPage:", i)
        for tag in page.tags:
            print(tag.name + ":", tag.value)
            
    # ser = tif.series[3]
    # h = tif.pages[5].asarray()
    for i, series in enumerate(tif.series):
        print("Series", i)
        print("pyramid?:", series.is_pyramidal)
        print("Dims:", series.dims)
        print("ndim:", series.ndim)
        #print("Coords:", series.coords)
        print("Axes:", series.axes)
        print("Shape:", series.shape)
        print("Len pages:", len(series.pages))
        print("Len levels:", len(series.levels))
        print("\n\n")


Page: 0
ImageWidth: 20827
ImageLength: 20827
BitsPerSample: 16
Compression: 1
PhotometricInterpretation: 1
ImageDescription: ImageJ=
hyperstack=true
images=2
channels=2
slices=1
frames=1
StripOffsets: (166922, 208576, 250230, 291884, 333538, 375192, 416846, 458500, 500154, 541808, 583462, 625116, 666770, 708424, 750078, 791732, 833386, 875040, 916694, 958348, 1000002, 1041656, 1083310, 1124964, 1166618, 1208272, 1249926, 1291580, 1333234, 1374888, 1416542, 1458196, 1499850, 1541504, 1583158, 1624812, 1666466, 1708120, 1749774, 1791428, 1833082, 1874736, 1916390, 1958044, 1999698, 2041352, 2083006, 2124660, 2166314, 2207968, 2249622, 2291276, 2332930, 2374584, 2416238, 2457892, 2499546, 2541200, 2582854, 2624508, 2666162, 2707816, 2749470, 2791124, 2832778, 2874432, 2916086, 2957740, 2999394, 3041048, 3082702, 3124356, 3166010, 3207664, 3249318, 3290972, 3332626, 3374280, 3415934, 3457588, 3499242, 3540896, 3582550, 3624204, 3665858, 3707512, 3749166, 3790820, 3832474, 3874128, 3915782

In [139]:
with TiffFile(img_path) as tif:
    print(tif.series[0].dataoffset)

None


In [ ]:
with TiffFile('/Users/hannahbolen/Desktop/image_analysis/o8p_day18.vsi') as tif:
    fh = tif.filehandle
    for page in tif.pages:
        for index, (offset, bytecount) in enumerate(
            zip(page.dataoffsets, page.databytecounts)
        ):
            _ = fh.seek(offset)
            data = fh.read(bytecount)
            tile, indices, shape = page.decode(
                data, index, jpegtables=page.jpegtables
             )

[[[[0 1 0]
   [0 1 0]
   [0 1 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 1 0]
   [0 1 0]
   [0 1 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 1 0]
   [0 1 0]
   [0 1 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]]] (0, 0, 0, 0, 0) (1, 375, 991, 3)
[[[[  8  13   7]
   [  0   2   0]
   [  5   7   4]
   ...
   [  6   5  11]
   [  8   7  13]
   [  4   3   9]]

  [[  8   8  10]
   [  0   0   2]
   [  6   6   6]
   ...
   [  5   4   9]
   [  4   3   8]
   [  3   2   7]]

  [[  5   2  11]
   [  2   0   8]
   [  6   4   9]
   ...
   [  6   7  11]
   [  4   5   9]
   [  4   5   9]]

  ...

  [[119 120 112]
   [125 126 120]
   [124 126 121]
   ...
   [104 113 110]
   [108 117 114]
   [105 111 111]]

  [[112 117 113]
   [117 121 120]
   [115 121 119]
   ...


In [141]:
memmap_volume = tifffile.memmap(img_path)

ValueError: image data are not memory-mappable